[package]
name = "cli"
version = "0.1.0"
authors = ["Brock Chelle <bchelle@ualberta.ca>"]
edition = "2018"

[dependencies]
strum = "0.20.0"
strum_macros = "0.20"
rand = { version = "0.6.5", features = ["wasm-bindgen"] }
